version: '3.9'
services:
  web:
      build:
            context: .
                  dockerfile: Dockerfile
                      command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
                          volumes:
                                - ./:/app
                                    ports:
                                          - '8000:8000'
                                              depends_on:
                                                    - db
                                                        env_file:
                                                              - .env
                                                                db:
                                                                    image: postgres:15-alpine
                                                                        restart: always
                                                                            volumes:
                                                                                  - pg_data:/var/lib/postgresql/data/
                                                                                      ports:
                                                                                            - '5432:5432'
                                                                                                environment:
                                                                                                      - POSTGRES_DB=groceries
                                                                                                            - POSTGRES_USER=postgres
                                                                                                                  - POSTGRES_PASSWORD=postgres
                                                                                                                        - PGDATA=/var/lib/postgresql/data/pgdata
                                                                                                                        volumes:
                                                                                                                          pg_data:
                                                                                                                          
